# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                  echo "APPWRITE_PROJECT_ID=community-app" >> .env
                  echo "APPWRITE_DATABASE_ID=communitydb" >> .env
                  echo "APPWRITE_API_KEY=placeholder" >> .env
                  echo "APPWRITE_URL=http://localhost/v1" >> .env

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: 3.24.0
            - run: flutter pub get
            # - run: flutter analyze # Uncomment this line to enable code analysis. It may fail the build if there are issues so use with intent.
            - run: flutter pub run build_runner build --delete-conflicting-outputs
            - run: flutter test
            # - run: flutter build web
